# -*- coding: utf-8 -*-
"""Cópia de Introdução Analise de Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UgQgDcS7jxKswVWXNZfo_2rHYAy6txoR

# Introdução a Análise de Dados

### Como funciona um Projeto de Análise de Dados?

Os projetos de Análise de Dados são na verdade Desafios das Empresas

### Desafio

- Empresa Vende Bermudas
- 5 Lojas
- Está querendo aumentar as vendas
- O que fazer?
- Informações Disponíveis: Base de Vendas

### Passo 1 - Trazer sua base de dados para o Python e ver o que tem nela
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
tabela = pd.read_excel('/Vendas (1).xlsx')
display(tabela)

"""### Passo 2 - Pegar um panorama geral sobre a sua base de dados"""

faturamento_total = tabela['Valor Final'].sum()
print(faturamento_total)

"""### Passo 3 - Começar sua análise Top -> Down"""

# faturamento por loja
faturamento_por_loja = tabela[["Valor Final", "ID Loja"]].groupby("ID Loja").sum()
display(faturamento_por_loja)

"""### Passo 4 - Entrar no detalhe pra entender"""

faturamento_por_produto = tabela[["ID Loja", "Produto", "Valor Final"]].groupby(["ID Loja", "Produto"]).sum()
display(faturamento_por_produto)

import plotly.express as px

"""Gráfico linha faturamento por Loja

foi observado um faturamento na loja iguatemi campinas
"""

dados_x = ['2019']
dados_y = [10,20,5,35]

fig = px.line(data_frame=faturamento_por_loja)
fig.show()

"""No gráfico de Barras

foi obeservado um pico de faturamento no dia 22 de Dezembro data proxima ao natal.

"""

import plotly.express as px
grafico = px.histogram(tabela, x="Data", y= "Valor Final")
grafico.show()

"""Tambem foi obeservado uma venda maior por produto nas Bermudas Lisas
Na Loja do iguatemi campinas
- E que nas outras lojas não possui o produto Bermuda Liso
"""

grafico = px.histogram(tabela, x="Produto",y="Valor Final")
grafico.show()